server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  websocket:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB

jwt:
  signerKey: ${SIGNING_KEY}
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

# Auction-specific configurations
auction:
  anti-snipe:
    default-extension-minutes: 5
    default-threshold-minutes: 2
    max-extensions: 3
  rate-limiting:
    max-bids-per-minute: 5
    max-bids-per-hour: 30
  reserve-price:
    enabled: true
  proxy-bidding:
    enabled: true
